#!/usr/bin/env bash
set -eo pipefail

# FOUND HERE: https://stackoverflow.com/questions/27242652/colorizing-golang-test-run-output
go $@ | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''

