#!/usr/bin/env bash
set -eo pipefail

# FOUND HERE: https://stackoverflow.com/questions/27242652/colorizing-golang-test-run-output
go $@ 2>&1 | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/ok/s//$(printf "\033[32mok\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''

