package events

const Clicked = "Clicked"
const CursorMoved = "CursorMoved"
const Dragged = "Dragged"
const EnterFrame = "EnterFrame"
const KeyDown = "KeyDown"
const KeyPressed = "KeyPressed"
const KeyUp = "KeyUp"
const Pressed = "Pressed"
const Released = "Released"

const MoveBack = "MoveBack"
const MoveDown = "MoveDown"
const MoveForward = "MoveForward"
const MoveLeft = "MoveLeft"
const MoveNext = "MoveNext"
const MovePrevious = "MovePrevious"
const MoveRight = "MoveRight"
const MoveUp = "MoveUp"
